type BuildEnvironment = Record<string, string | undefined>

export const SYNTHETIC_BUILD_URL = 'https://concept-portal-build.invalid'
export const SYNTHETIC_BUILD_KEY = 'sb_publishable_synthetic_build_only_never-deploy'

export type ProductionConfig = {
  supabaseOrigin: string
}

function required(environment: BuildEnvironment, name: string): string {
  const value = environment[name]?.trim()
  if (!value) throw new Error(`Production build requires ${name}.`)
  return value
}

function hostedSupabaseOrigin(value: string): string {
  let url: URL
  try {
    url = new URL(value)
  } catch {
    throw new Error('VITE_SUPABASE_URL must be a valid HTTPS URL.')
  }

  if (url.protocol !== 'https:') {
    throw new Error('VITE_SUPABASE_URL must use HTTPS.')
  }
  if (value !== url.origin || url.username || url.password || url.port) {
    throw new Error('VITE_SUPABASE_URL must be an exact origin without credentials, a path, query, or fragment.')
  }
  if (!/^[a-z0-9]{20}\.supabase\.co$/.test(url.hostname)) {
    throw new Error('VITE_SUPABASE_URL must use the exact hosted Supabase project origin.')
  }
  return url.origin
}

function jwtRole(value: string): string | null {
  const parts = value.split('.')
  if (parts.length !== 3) return null
  try {
    const payload = JSON.parse(Buffer.from(parts[1], 'base64url').toString('utf8')) as unknown
    if (typeof payload !== 'object' || payload === null || Array.isArray(payload)) return null
    return typeof (payload as { role?: unknown }).role === 'string'
      ? (payload as { role: string }).role
      : null
  } catch {
    return null
  }
}

function validateBrowserKey(environment: BuildEnvironment): void {
  const publishable = environment.VITE_SUPABASE_PUBLISHABLE_KEY?.trim()
  const legacyAnon = environment.VITE_SUPABASE_ANON_KEY?.trim()
  if (!publishable && !legacyAnon) {
    throw new Error('Production build requires a browser-safe Supabase publishable key.')
  }
  if (publishable?.startsWith('sb_secret_') || legacyAnon?.startsWith('sb_secret_')) {
    throw new Error('A Supabase secret key must never be bundled into the browser.')
  }

  if (publishable) {
    if (!/^sb_publishable_[A-Za-z0-9_-]{20,}$/.test(publishable)) {
      throw new Error('VITE_SUPABASE_PUBLISHABLE_KEY is not a valid Supabase publishable key.')
    }
  }

  if (!legacyAnon) return
  const role = jwtRole(legacyAnon)
  if (role !== 'anon') {
    throw new Error(
      role === 'service_role'
        ? 'A legacy service_role key must never be bundled into the browser.'
        : 'VITE_SUPABASE_ANON_KEY must be a legacy Supabase anon JWT.',
    )
  }
}

export function validateProductionConfig(environment: BuildEnvironment): ProductionConfig {
  if (environment.CONCEPT_SYNTHETIC_BUILD === '1') {
    if (
      environment.VITE_SUPABASE_URL !== SYNTHETIC_BUILD_URL ||
      environment.VITE_SUPABASE_PUBLISHABLE_KEY !== SYNTHETIC_BUILD_KEY ||
      environment.VITE_SUPABASE_ANON_KEY
    ) {
      throw new Error('The synthetic build flag accepts only the repository test sentinels.')
    }
    return { supabaseOrigin: SYNTHETIC_BUILD_URL }
  }

  const supabaseOrigin = hostedSupabaseOrigin(required(environment, 'VITE_SUPABASE_URL'))
  validateBrowserKey(environment)
  return { supabaseOrigin }
}

export function createNetlifyHeaders(supabaseOrigin: string): string {
  const contentSecurityPolicy = [
    "default-src 'self'",
    "base-uri 'self'",
    `connect-src 'self' ${supabaseOrigin}`,
    "font-src 'self'",
    "form-action 'self'",
    "frame-ancestors 'none'",
    "img-src 'self' data:",
    "object-src 'none'",
    "script-src 'self'",
    "style-src 'self'",
  ].join('; ')

  return `# Generated by the production Vite build. Do not edit the deployed copy.\n/*\n  Content-Security-Policy: ${contentSecurityPolicy}\n  Cache-Control: no-store\n  Permissions-Policy: camera=(), geolocation=(), microphone=()\n  Referrer-Policy: no-referrer\n  Strict-Transport-Security: max-age=31536000\n  X-Content-Type-Options: nosniff\n  X-Frame-Options: DENY\n\n/assets/*\n  Cache-Control: public, max-age=31536000, immutable\n\n/index.html\n  Cache-Control: no-store\n`
}
